name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 * * * *" # This runs the action every day at midnight
  workflow_dispatch: # Allows you to manually trigger the sync as well

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add upstream remote
        run: git remote add upstream https://github.com/ArpitMishra17/Datathon_Crypto_Scammers

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main # Or `upstream/master`

      - name: Push changes
        run: git push origin main # Or `git push origin master`
